modLoader="javafml"
loaderVersion="[35,)"
license="MIT"
issueTrackerURL="https://github.com/JackyyTV/SimpleSponge/issues"

[[mods]]
modId="simplesponge"
version="5.0"
displayName="Simple Sponge"
displayURL="https://github.com/JackyyTV/SimpleSponge"
logoFile="logo.png"
credits="OpenBlocks source code and TurkeyDev"
authors="Jackyy, ThatGamerBlue"
description='''
OpenBlocks Sponge port for 1.10+, with some extra sprinkles!
'''

[[dependencies.simplesponge]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesponge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplesponge]]
    modId="gunpowderlib"
    mandatory=true
    versionRange="[1.16.4-1.1,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.simplesponge]]
    modId="openblocks"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
